#!/bin/bash
#
# Install desktop apllications

# Terminator
sudo apt install terminator

# Synapse
sudo apt install synapse

# Brave browser
wget -qO - https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com `lsb_release -sc` main" | sudo tee /etc/apt/sources.list.d/brave.list
sudo apt update
sudo apt install brave-browser brave-keyring
# uninstall
#sudo apt remove --autoremove brave-browser brave-keyring

# Sublime text 3
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update
sudo apt install sublime-text
# uninstall
#sudo apt remove --autoremove sublime-text

# Pdftk
# pdftk-java in 18.10 Cosmic repo from CZ mirror
cd ~/Downloads
sudo apt install default-jre-headless libbcprov-java libcommons-lang3-java xpdf-utils
wget -q - http://cz.archive.ubuntu.com/ubuntu/pool/universe/p/pdftk-java/pdftk-java_3.0.2-2_all.deb
sudo dpkg -i pdftk-java_3.0.2-2_all.deb
sudo apt -f install
rm pdftk-java_3.0.2-2_all.deb

# Imagemagick
sudo apt install imagemagick

# Evince
sudo apt install evince

# Redshift
sudo apt install redshift-gtk
# TODO: adding geoclue config for finding location or static lon / lat redshift config
#sudo tee -a /etc/geoclue/geoclue.conf <<EOF
#
#[redshift]
#allowed=true
#system=false
#users=
#EOF

# Safeeyes
sudo add-apt-repository ppa:slgobinath/safeeyes
sudo apt update
sudo apt install safeeyes
# uninstall
#sudo apt remove safeeyes

# WPS office
# TODO: snapd download slow
#sudo apt install snapd
#sudo snap install wps-office
cd ~/Downloads
wget -q - http://kdl.cc.ksosoft.com/wps-community/download/6757/wps-office_10.1.0.6757_amd64.deb
sudo dpkg -i wps-office_10.1.0.6757_amd64.deb
sudo apt -f install
rm wps-office_10.1.0.6757_amd64.deb

# Fonts
# Inconsolata, Open Sans
cd ~/Downloads
wget -q - https://www.levien.com/type/myfonts/Inconsolata.otf
wget -q - https://www.fontsquirrel.com/fonts/download/open-sans
unzip open-sans && rm open-sans
sudo chown root:root Inconsolata.otf
sudo chown root:root OpenSans*.ttf
sudo chmod 644 Inconsolata.otf
sudo chmod 644 OpenSans*.ttf
sudo mkdir /usr/share/fonts/opentype
sudo mkdir /usr/share/fonts/truetype/open-sans
sudo mv Inconsolata.otf /usr/share/fonts/opentype
sudo mv OpenSans*.ttf /usr/share/fonts/truetype/open-sans
sudo mv 'Apache License.txt' /usr/share/fonts/truetype/open-sans
sudo fc-cache -f -v

# Nordvpn
cd ~/Downloads
wget https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb
sudo dpkg -i nordvpn-release_1.0.0_all.deb
sudo apt install nordvpn
sudo apt -f install
rm nordvpn-release_1.0.0_all.deb
